name: flutter_basic_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  change_app_package_name: ^1.1.0
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0
  get_it: ^7.6.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  mockito: any
  toast: ^0.3.0

dev_dependencies:
  flutter_lints: ^2.0.0

  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
